name: Build Dynamics Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: henrij22/ikarus-dynamics:latest
          secrets: |
            "github_token=${{ secrets.TIK_ACCESS_TOKEN }}"
          build-args: |
            compiler="clang"
            ccompiler="clang-16"
            cppcompiler="clang++-16"
          context: "{{defaultContext}}:dynamics"
          
        #  jobs:
#    build-docker-debian:
#      runs-on: ubuntu-latest
# 
    #  steps:
    #    - uses: actions/checkout@v4
    #      with:
    #       secrets: |
    #         "github_token=${{ secrets.TIK_ACCESS_TOKEN }}"
    #    - name: Build the extra image
    #      working-directory: ./dynamics
    #      run: |
    #       docker build . --file Dockerfile --tag henrij22/ikarus-dynamics:latest --build-arg compiler="clang" 
    # --build-arg ccompiler="clang-16" --build-arg cppcompiler="clang++-16"
    #    - name: Docker Login
    #      uses: azure/docker-login@v1
    #      with:
    #        username: ${{ secrets.DOCKER_USERNAME }}
    #        password: ${{ secrets.DOCKER_PASSWORD }}
    #    - name: Publish the Docker image
    #      run: |
    #        henrij22/ikarus-dynamics:latest
