 name: Build Development Windows image
 on:
   push:
    #  branches:
    #    - 'main'
     paths:
      - windows/**  

   workflow_dispatch:

 jobs:
   build-docker-debian:
     runs-on: windows-2019

     steps:
       - uses: actions/checkout@v4
       - name: Build the Windows Docker image
         working-directory: ./windows
         run: |
           docker build . --file Dockerfile --tag henrij22/windows:latest


       - name: Docker Login
         uses: azure/docker-login@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Publish the Docker image
         run: |
           docker push henrij22/windows:latest  
             
